[Incoming]
Protocol = "tcp"
Host = "m15.cloudmqtt.com"
Port = 15634
Username = "rmjbxjjs"
Password = "srui94pczkfM"
Qos = 0
KeepAlive = 3600
MqttClientId = "IncomingDataSubscriber"
Topic = "DataTopic"

[Response]
Protocol = "tcp"
Host = "m15.cloudmqtt.com"
Port = 15634
Username = "rmjbxjjs"
Password = "srui94pczkfM"
Qos = 0
KeepAlive = 3600
MqttClientId = "CommandResponseSubscriber"
Topic = "ResponseTopic"